### PR TITLE
get keep-alive working outside of homebridge and refactor sip api

### PR DESCRIPTION
**Pull request by bourdakos1**
There's probably a lot of issues with this. Mainly, I don't really know what I'm doing with RxJs, but I figured I should get your eyes on this since I moved a lot of stuff around already haha

### CODE REVIEW

**Comment by bourdakos1** [comment]
The main changes are:
- setting an open sip port for normal and tls calls (I was getting a lot of port in use errors with just the default)
- sip session takes a video and audio socket so that it will automatically send the keep alive messages
- I added a streaming example demo

**Comment by dgreif** [comment]
Thanks for the PR! I'm busy tonight but I will take a look at it tomorrow afternoon.  Really appreciate your help 🙇

**Comment by dgreif** [comment]
@bourdakos1 I'm going to merge this to a branch and do some cleanup before I merge to master.  Thanks for getting everything in place!  I may change some of the naming on things but in general I think it's close.  Probably have a release with the updates tomorrow.

**Comment by omerdn1** [comment]
awesome job on this one @bourdakos1.
thanks for pushing this forward

**Pull request merged**
