### PR TITLE
The Push Event for Ding changed

### PR DESCRIPTION
**Pull request by biede88**
`Received push notification in unknown format
{"data":{"version":"2.0.0","data":"{\"device\":{\"e2ee_enabled\":false,\"id\":123456,\"kind\":\"intercom_handset_audio\",\"name\":\"Door\"},\"event\":{\"ding\":{\"id\":\"738958353620123456\",\"created_at\":\"2024-07-16T10:38:11Z\",\"subtype\":\"button_p>`

tested with intercom

### CODE REVIEW

**Comment by tsightler** [comment]
This PR is incorrect as it's replacing Ding for all device types, not just intercom.  We've known that the push notifications were changing as part of the migration to FCMv1 API.  I've done a good bit of work and beta branch already has most of the required changes, but as I did not have access to an intercom, it was difficult to know for sure what the new intercom format was.

Based on what you've put here, it seems that Doorbell dings are now a different type from intercom dings as doorbells now use "com.ring.pn.live-event.ding". so that fits with the model that intercom might is "com.ring.pn.live-event.intercom".

Is there any chance you could provide the full output of the push notification as the one above is partially cut off.  Although it looks like it's the same as the new doorbell ding format, which makes total sense, it would be good to know for sure.  I would also love to get the entire format of the unlock push notification as well (I believe it is type 'com.ring.pn.intercom.virtual.unlock')

**Comment by tsightler** [comment]
@biede88 Sorry to ping again, but it would really help us resolve this if you could provide the full output of the push notification content rather than the truncated one you posted above.

**Comment by biede88** [comment]
Yes, with pleasure. Does that help?

Ding:
```
[7/22/2024, 1:00:28 AM] [Ring] Received push notification with unknown category: com.ring.pn.live-event.intercom
[7/22/2024, 1:00:28 AM] [Ring] {"data":{"version":"2.0.0","data":"{\"device\":{\"e2ee_enabled\":false,\"id\":298361211,\"kind\":\"intercom_handset_audio\",\"name\":\"Entrance\"},\"event\":{\"ding\":{\"id\":\"7394367000199864699\",\"created_at\":\"2024-07-22T08:00:28.182Z\",\"subtype\":\"ding\"},\"is_sidewalk\":false,\"live_session\":{\"streaming_data_hash\":\"sh-v1|wVrxK3siWHM-rDBmVyqHvnthjtKk6NzDBahF23xoEPqN9UQ7Oyn_4dg5XgUDGPZsgB1hrMe3e8yU4R-iiQJLArIrb9rKGmhT3OlzVT8WnX8kopIFZKHRm9lHqzsBQ-Xj0t_BIuK5RBAoFLHYOyF4d9zp19MkDu9dGUQWWkMoW-zTbbSCimOCxTeOxo8jsLf3yfOG5UadzYGLBN-91tQ_6zIbU0r5RXdh4z1IXmnpNJSl-61iupCVYdhMWdGtmelMhR2tDO32pk0647I286tyCl0pM2MMsqMl_XdEZxA4vMI2fIA47FZkP7Xvuj21Mbaj9--bMOOT9HXfH3NnpuMTIs_QkKnWCrc0VGn_YUNywuSySC_qv4tCjco7Uto7xFLVYwjAJmKFCMsG3cqz00OSR8j9MbLnZLH9-MDyDUewD28pxGq7bM1nHsUqKN0kTdqeEd_gyLmsAAvnEo-ZQEumXID8hcvZxKFdVVKAFdnk4cD8wrL6t2w5KUXQCW54-olZGTK32e9pY6MbdOHeWTe1VnXM4TSG7P0Sv0MgfUR8ZrsH8-4ov-xaiWL6DBeO0lvwIejKyr56IworUhVzNSZhGOTBPgEB5-T-rxUiGRBedv35x_3xETpRPurEKJ3rRPA06VtD6vyY5-NXcMrEErZHZI_ob60JYT8-BqiY2SxYchqlKTm8zb00dPO6fZXl12U0j6OS7BIIYo2wSGWK8enlDjrTgLFtd0RIqtYIYaZrcxa2GJVaK_u7_UD_l5TnNh1jHrwLXNnSQJV_ife4beNbMOaaWzCuVwmbsOx1Mk84xz9jagMslCYPn1gi3AfKSlewwVTr7TIwSxVjOnVxpBIDydzVIhJliyh95q8Uy7XFm3CrwQbCLXSaEKmARiIFtq773zhuwBv2sH6N1NaVyxtLd1U0FQxipwz8f0SgEaoInUfxeWPRxKNHLkzGR2OK9PLLJN-pWJPurrhjbHZ5tlL-0xuI1IFXTlpU9J2mmobdjy1pcy8EZndZKMTCaR1puRIBsn0hZhErpzBZvdceLZ-Jh5iIO9tQr4mG1pRL_A7wjaTfqhja6oKobjQkdFZEALKzsyp5PsMN7EzRBU9Ckt6V0fZ-b1oJfOyN0ldmtP7Cyqmb5oplr5Ukn07ROmBs78JIH5XetaikmKT4Ib0IzEC_Mf8LpYRx3K-hhYIpTWEhQLwzyQpBsToLhdcC8t352Ge6ON-RwDDpQlQe8tp5rMVSMHryciOfSyVIh3K5GIKJJ5YSBlImoC8exECYcnu-4YW7iRp2\",\"active_streaming_profile\":\"rms\",\"default_audio_route\":\"quiet_speaker\",\"max_duration\":600}},\"location\":{\"id\":\"99b3e09a-948d-44b4-bab5-0cc40eee9b36\"}}","analytics":"{\"server_correlation_id\":\"e1a0631b-e19e-44bc-ad62-45133026e18e\",\"server_id\":\"com.ring.pns\",\"subcategory\":\"ding\",\"triggered_at\":1721635228182,\"sent_at\":1721635228372,\"referring_item_type\":\"device_id\",\"referring_item_id\":\"298361210\"}","android_config":"{\"category\":\"com.ring.pn.live-event.intercom\",\"body\":\"🔔 Someone is at your Entrance\"}"},"from":"876313859328","priority":"normal","fcmMessageId":"7261c9ca-85f4-4079-b91a-4cf1b4a98ebc"}
```

Unlock from App:

```
 [7/22/2024, 1:00:39 AM] [Ring] Received push notification in unknown format
 [7/22/2024, 1:00:39 AM] [Ring] {"data":{"gcmData":"{\"aps\":{\"alert\":\"Your Entrance in Berlin was used to unlock the entrance on 7/22/24 at 10:00 AM\"},\"action\":\"com.ring.push.INTERCOM_UNLOCK_FROM_APP\",\"alarm_meta\":{\"location_id\":\"99b3e09a-948d-44b4-bab5-0cc40eee9b36\",\"device_zid\":298361211}}"},"from":"876313859328","priority":"normal","fcmMessageId":"250b7328-7664-4109-a67a-d516ae75c640"}
```

Unlock via Homebridge:
```
[7/22/2024, 1:03:43 AM] [Ring] Unlocking Entrance
[7/22/2024, 1:03:45 AM] [Ring] Unlock response: {"jsonrpc":"2.0","result":{"code":0},"id":null,"responseTimestamp":1721635425000}
[7/22/2024, 1:03:46 AM] [Ring] Received push notification in unknown format
[7/22/2024, 1:03:46 AM] [Ring] {"data":{"gcmData":"{\"aps\":{\"alert\":\"Your Entrance in Berlin was used to unlock the entrance on 7/22/24 at 10:03 AM\"},\"action\":\"com.ring.push.INTERCOM_UNLOCK_FROM_APP\",\"alarm_meta\":{\"location_id\":\"99b3e09a-948d-44b4-bab5-0cc40eee9b36\",\"device_zid\":298361211}}"},"from":"876313859328","priority":"normal","fcmMessageId":"a1256dff-1205-45e0-819c-7f21c041a5e7"}
```

**Comment by tsightler** [comment]
Thank you very much @biede88, that helps a lot.  There may still be another we need, but I think this is enough to get us going with something.  Hopefully we can get a new version out soon.

**Comment by dgreif** [comment]
@biede88 thank you so much for the examples!! I've released a new beta version with updates which should get both intercom dings and intercom unlocks working properly. I'm going to go ahead and close this PR as the final changes were a bit more complicated, but I couldn't have done it without your help ❤

**Pull request closed without merging**
