### PR TITLE
Use Thermostat accessory to choose Snooze duration

### PR DESCRIPTION
**Pull request by dxdc**
- An improved variant of https://github.com/dgreif/ring/pull/365 OR https://github.com/dgreif/ring/pull/370
- Allows to set snooze hours in terms of degrees
- Simple toggle on/off button
- Working, but needs additional testing

### TODO: 
- Temperature units need to be converted to a normal standard (ideally celsius). I have tried setting `TemperatureDisplayUnits` but it didn't work so far.

https://github.com/homebridge/HAP-NodeJS/blob/5cacbd400bc15785f372eefb83bc40a5e21a439a/src/lib/gen/HomeKit.ts#L2953-L2975

- Might benefit from having the target temperature decoupled from the snooze duration.
- Config option to turn on/off as switch

### CODE REVIEW

**Comment by dgreif** [comment]
Could get weird if you consider Celsius can farenheit... I’m fine with just doing the valve.

**Comment by dxdc** [comment]
> Could get weird if you consider Celsius can farenheit... I’m fine with just doing the valve.

Yeah, that's what I meant by:
> Temperature units need to be converted to a normal standard (ideally celsius). I have tried setting TemperatureDisplayUnits but it didn't work so far.

It seems there should be a way to lock it. Without that, it is weird, but if there is a way to convert it fully to show Celsius only then it would be perfect.

**Comment by dxdc** [comment]
@dgreif another option would be in the config, user could choose C or F as their default HK display units. Then, we can simply multiply all the units to convert.

Not sure if there is a cleaner solution? I do like the simplicity of this option though.

**Comment by dgreif** [comment]
I think the valve works nicely because it has the time remaining built in. Every solution has pluses and minuses 😕

**Comment by dxdc** [comment]
@dgreif give this latest version a try, if you would. I hard-coded `useF` but I think the functionality works really well actually. Curious on your take.

Something also off with the `elapsedTime` function... I saw this.
```
1|homebridge  | [7/11/2020, 3:53:32 PM] [Ring] Chime snoozed for 4:05:60
```

**Comment by dxdc** [comment]
> I think the valve works nicely because it has the time remaining built in

Agree with this, but it's set to the temperature now. So, if 24 hours remaining, 24 degrees, etc.

**Comment by dgreif** [comment]
@dxdc I'm still stuck on the fact that it can get messed up with F vs C.  I think we should take a step back and talk about why this is needed again. The current switch allows you to create automations that will turn the switch on and then turn it off after X minutes, which seems like it should cover most use cases in my mind.  For more complex automations, I assume you could use Node Red to handle the duration aspect.  What's the scenario in which the valve or thermostat is really beneficial?

**Comment by dgreif** [comment]
@dxdc thoughts on closing this since we never made a decision on the best way to implement?

**Comment by dxdc** [comment]
@dgreif Sorry for slacking on this one, I've been really busy the past few months. I experimented with it some more, but HK still lacks a great way to set a timer and everything else I've tried seems somewhat clunky and non-intuitive.

So, I think it's fine to close the issue for now.

I have implemented a variant of my idea inside NodeRED, which essentially listens for motion alerts, and then, if >X come in a fixed time window, it turns on the snooze and keeps it on if motion alerts continue at that rate -- and it turns them off afterward. It may still need some fine tuning, but it is workable.

One thing that could improve my set up is having a trigger that fires only when the Chime is played with a specific alert. I tried the "Speaker" sensor, but that didn't seem to fire when motion happened. Do you know if such a sensor exists? I would be fine with having a Motion sensor inside the Chime to detect when the Motion is played.

This all being said, I may be moving to more of a speech-to-text solution. E.g. "Motion at the Front", via Sonos. It may be more intuitive than these dumb chimes that are only good for a ring or motion MP3 :)

**Comment by dgreif** [comment]
@dxdc no worries about being busy, I've been in the same boat 😄 .  I don't think there is any way to detect which sounds are being played on the Chime, only to tell it _to play a sound_, so I'm not sure there is a better solution on that front.  I haven't had any more complaints about this specific snooze duration issue, so I think we are good to close this.  I may finally install Node Red sometime soon as I also need to start setting up some more advanced automations and just can't quite do it all with HomeKit.  Good luck with the Sonos setup! And thanks for all your hard work looking into this and other issues on the repo 🙇

**Pull request closed without merging**
