### PR TITLE
feat(api): enable retrieve/reuse sessions (#337)

### PR DESCRIPTION
**Pull request by djm181**
Allows for sessions to be retrieved and subsequently reused by the client. Ring limits session requests and this enables getting around the 406 errors that the API starts to throw.

If a single IP makes too many `/session` requests (I think the limit is maybe 50 in a 24-hour period) then you run into #337 and #247 errors. But the session response is fairly status so we can avoid the request if we know that the session is good.

### CODE REVIEW

**Comment by djm181** [comment]
@dgreif - first PR on this repo so please let me know if there is anything else you want me to take care of for this to be ready for review.

**Comment by dgreif** [comment]
Sorry for the delay @djm181!  I'm curious what the use case is for this change.  Are you simply starting/stopping a lot as you develop another project?  I'm wondering if there is a better way to fetch current sessions from Ring so that we don't have to store the session elsewhere.  Also curious why you added the `[extra_meta:string] : any`.  If there are other details that you are seeing, i'd prefer to add the specific types.

**Comment by djm181** [comment]
So as I mentioned in my feature request #378 (which I do plan to send in a PR for), I want to be able to disconnect the `RingApi` instance and reconnect with different options - if this is happening frequently then one can run into the limit, but it's definitely exacerbated during development. I would be a little surprised if Ring allowed fetching of sessions because the response includes an authentication token (although it's unclear what this is for).

As for the extra meta, that was a lazy catch-all but you are right - we should just introduce the missing fields. I'll push an update with those now.

**Comment by dgreif** [comment]
Sounds good. I am hoping to get some time for Ring this weekend so I may be able to assess the session situation a little closer. Users sometimes run into the limit in homebridge ring if they have a bad plugin continually crashing their homebridge server, so this is definitely something I would like to address if possible. Do you use any of the values from the session response in your project? What is it that you are implementing if you don’t mind me asking?

**Comment by dgreif** [comment]
I did some testing this morning and it looks like the session only needs to be created if Ring doesn't recognize the `hardware_id`.  The rest client will now only create a new session if it receives a response indicating that a session wasn't found.  I also added `api.getProfile()` which allows you to get the same profile response that the session endpoint provided.  These changes are pushed to master, and I plan to do a release today or tomorrow after I get a few more changes in.  Thanks for encouraging this change, I think it will be very useful for all users!

**Comment by dgreif** [comment]
Changes released in v`9.4.0`

**Pull request closed without merging**
