### PR TITLE
Ring Chime support

### PR DESCRIPTION
**Pull request by jadenv**
Firstly, thank you for this awesome repo @dgreif. Definitely one of the highest quality homebridge repos to date!

Hoping I can contribute here a bit for issue https://github.com/dgreif/ring/issues/262. I haven't yet worked with a speaker device type like you had mentioned in that issue, so I figured I would try to implement the Chime API side of things and then discuss the homebridge side a bit further with you.

Currently with this PR, a chime has these abilities:
- Play a motion sound
- Play a ding sound
- Set a snooze interval
- Clear a snooze interval
- Fetch available ringtones
- Update chime with new volume/ringtones

I added an example of setting a new ringtone, then the `playSound` for both dings and motion events.

It would be awesome to have the ability to trigger `playSound` by way of a HomeKit automation so other motion sensors, timers, miscellaneous events could also notify the house using the chime. Like I said, I haven't worked with a speaker type in homebridge before, so wondering if that is the best approach or if something like a momentary switch type of deal would be better to play a notification sound.

Totally game for any other ideas you have!

### CODE REVIEW

**Comment by dgreif** [comment]
@jadenv thanks for the PR, it is very much appreciated!  I've been planning to work on chimes for a while but just haven't found the time.  This is a really solid start and goes beyond the initial scope that I had in mind.  I had no idea you could trigger sounds via the API, but that will definitely be a useful feature.  Here are the main services that I think would be good to have in the homebridge plugin:

1) A switch for activating/deactivating ding event chimes
2) A switch for activating/deactivating motion event chimes (might have to use snooze here, not sure)
3) A switch for triggering a ding sound (turns off automatically after being turned on)
4) A switch for triggering a motion sound (turns off automatically after being turned on)
5) A speaker that allows volume to be controlled

I'll leave this PR open for now if you want to take a stab at the accessory implementation.  Otherwise, I'll pick it up when I have free time.  Thanks for all your work so far!

**Comment by ifeign** [comment]
All these feature ideas are great. I wanted to make one other suggestion - the new Chime Pro has a night light, could this be exposed as a light accessory?

**Comment by dgreif** [comment]
@jadenv I haven't forgotten about this PR!  I got really deep into live streaming and wanted to completely finish that off before moving on to other features.  I'm planning to take a look at the chime over the next week or two.  I'll probably merge this PR into a branch and build the homebridge accessory myself.  Thanks again for getting all this implemented, it's a fantastic start!

**Comment by dgreif** [comment]
@jadenv thank you so much for implementing the chime api!! What you have here so far is fantastic!  I should be able to get a good chunk of the homebridge accessory done tomorrow

**Comment by jadenv** [comment]
@dgreif Thank you for finishing out the homebridge accessory piece! I just installed the latest release, and it works perfect. Can't wait to start using this in automations!

Cheers!! 🍻

**Pull request merged**
